// Generated by Haxe 3.3.0
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	window.addEventListener("load",Main.onLoaded);
};
Main.onLoaded = function(event) {
	var data = { name : "Kenta Sakata", friends : [{ name : "Iwao", age : "36"}]};
	new vue_Vue({ el : "#app", data : data});
};
var vue_Vue = function(options) {
	this._vue = new Vue(options);
};
vue_Vue.prototype = {
	get_data: function() {
		return this._vue.$data;
	}
	,get_el: function() {
		return this._vue.$el;
	}
	,get_index: function() {
		return this._vue.$index;
	}
	,get_options: function() {
		return this._vue.$options;
	}
	,get_parent: function() {
		return this._vue.$parent;
	}
	,get_root: function() {
		return this._vue.$root;
	}
	,get_compiler: function() {
		return this._vue.$compiler;
	}
	,watch: function(s,cb) {
		this._vue.$watch(s, cb);
	}
	,unwatch: function(s,cb) {
		this._vue.$unwatch(s, cb);
	}
	,get: function(s) {
		return this._vue.$get(s);
	}
	,set: function(keypath,value) {
		this._vue.$set(keypath, value);
	}
	,dispatch: function(event,arg) {
		this._vue.$dispatch(event, arg);
	}
	,bloadcast: function(event,arg) {
		this._vue.$bloadcast(event, arg);
	}
	,emit: function(event,arg) {
		this._vue.$emit(event, arg);
	}
	,on: function(event,cb) {
		this._vue.$on(event, cb);
	}
	,once: function(event,cb) {
		this._vue.$once(event, cb);
	}
	,off: function(event,cb) {
		this._vue.$off(event, cb);
	}
	,appendTo: function(to) {
		this._vue.$appendTo(to);
	}
	,before: function(to) {
		this._vue.$before(to);
	}
	,after: function(to) {
		this._vue.$after(to);
	}
	,remove: function() {
		this._vue.$remove();
	}
	,destroy: function() {
		this._vue.$destroy();
	}
};
Main.main();
})();
